name: Test Project

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: node:20 # This line already provides Node.js v20
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm ci

      - name: Run Tests
        run: npm test

      - name: Build Project
        run: npm run build
# name: Test Project

# on:
#   pull_request:
#     branches:
#       - main

# jobs:
#   test:
#     runs-on: ubuntu-latest
#     container:
#       image: node:20
#     steps:
#       - uses: actions/checkout@v3
#         with:
#           node-version: 20
#       - run: npm ci
#       - run: npm test
#       - run: npm run build
